name: Call refresh tokens

on:
  schedule:
    - cron: '25 7,15,23 * * *'
  push:
    branches:
      - master
    paths:
      - 'assets/refresh-tokens'

jobs:
  call-refresh-tokens:
    name: Fetch refresh tokens on cloud function
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL POST
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          SERVER_OPERATOR_TOKEN: ${{ secrets.SERVER_OPERATOR_TOKEN }}
        run: |
          curl --silent --show-error --fail \
            -H "X-Operator-Token: $SERVER_OPERATOR_TOKEN" \
            -X POST https://us-central1-$FIREBASE_PROJECT_ID.cloudfunctions.net/app/ecom/refresh-tokens
